"""
Django settings for proj project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

print BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y@bzrocszm8#r_cyt@gsof+#29kcufqv6@z#l*7z@_e!5m8boj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'normais',
    'automaticas',
    'leaflet',
    'django_extensions',
    'paintstore',    
    
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+'/templates/'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases



DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.postgresql_psycopg2', 
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'FireMonitor',                      
        'USER': 'postgres',
        'PASSWORD': 'wilci5w7',
        'HOST': '10.3.0.29',                   
        'PORT': '5432',                     
    }
}


STATICFILES_DIRS = (
    BASE_DIR+ "/normais/static/plugins/",
    BASE_DIR+ "/normais/static/css/",
    BASE_DIR+ "/normais/static/js/",
    BASE_DIR+ "/normais/static/img/",
    BASE_DIR+ "/normais/static/js//typeahead/",
    BASE_DIR+ "/normais/static/fonts/",
    BASE_DIR+ "/normais/static/plugins/bootstrap/",
    BASE_DIR+ "/normais/static/plugins/bootstrapvalidator/",
    BASE_DIR+ "/normais/static/plugins/d3/",
    BASE_DIR+ "/normais/static/plugins/fatatables/",
    BASE_DIR+ "/normais/static/plugins/fancybox/",
    BASE_DIR+ "/normais/static/plugins/fineuploader/",
    BASE_DIR+ "/normais/static/plugins/flot/",
    BASE_DIR+ "/normais/static/plugins/fullcalendar/",
    BASE_DIR+ "/normais/static/plugins/jquery/",
    BASE_DIR+ "/normais/static/plugins/jQuery-Knob/",
    BASE_DIR+ "/normais/static/plugins/jquery-ui/",
    BASE_DIR+ "/normais/static/plugins/jquery-ui-timepicker-addon/",
    BASE_DIR+ "/normais/static/plugins/justified-gallery/",
    BASE_DIR+ "/normais/static/plugins/moment/",
    BASE_DIR+ "/normais/static/plugins/morris/",
    BASE_DIR+ "/normais/static/plugins/raphael/",
    BASE_DIR+ "/normais/static/plugins/select2/",
    BASE_DIR+ "/normais/static/plugins/sparkline/",
    BASE_DIR+ "/normais/static/plugins/tinymce/",
    BASE_DIR+ "/normais/static/plugins/xcharts/",
    BASE_DIR+ "/normais/static/js/highcharts/js/",
)


LANGUAGE_CODE = 'pt-br'
ugettext = lambda s: s
LANGUAGES = (
    ('en', ugettext('English')),
    ('pt', ugettext('Portugues')),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


GRAPPELLI_ADMIN_TITLE= u'FIRE-MONITOR -  Terravision'

STATIC_URL = '/static/'
