# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0021_auto_20151201_1853'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ptomonit',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='medicao',
            name='vlr',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
    ]
