# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0014_auto_20160224_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Classe VMP',
                'verbose_name_plural': 'Classe VMP',
            },
        ),
        migrations.CreateModel(
            name='Legislacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Legisla\xe7\xe3o',
                'verbose_name_plural': 'Legisla\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Limites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_max', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('vlr_min', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('classe_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param.Classe', verbose_name='Classe')),
                ('legislacao_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param.Legislacao', verbose_name='Legislac\xe3o')),
                ('parametro_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param.Param', verbose_name=b'Parametro')),
            ],
            options={
                'verbose_name': 'Limites',
                'verbose_name_plural': 'Limites',
            },
        ),
    ]
