# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0015_classe_legislacao_limites'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='decimais',
            field=models.IntegerField(default=0),
        ),
    ]
